### ISSUE TITLE
AttributeError: 'Connection' object has no attribute 'sshpass_pipe'

### ISSUE THREAD

**Issue by tlc** [andreasscherbaum/ansible-lxc-ssh#20] opened 2019-02-26 16:51 UTC
Having this issue using

$ ansible-playbook --version
ansible-playbook 2.7.8

I am using -k and a password.

```
TASK [robertdebock.bootstrap : register apk] ***********************************
task path: /home/tlc/playbooks/roles/robertdebock.bootstrap/tasks/main.yml:27
XXX connect
<reducto.home> ESTABLISH SSH CONNECTION FOR USER: root
<reducto.home> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/home/tlc/.ansible/cp/00f460a8d5 -tt reducto.home 'which lxc'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 553, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 846, in _get_connection
    ansible_playbook_pid=to_text(os.getppid())
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 397, in get
    obj = obj(*args, **kwargs)
  File "/home/tlc/playbooks/plugins/lxc_ssh.py", line 155, in __init__
    (returncode2, stdout2, stderr2) = self._exec_command("which lxc", None, False)
  File "/home/tlc/playbooks/plugins/lxc_ssh.py", line 1094, in _exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/home/tlc/playbooks/plugins/lxc_ssh.py", line 101, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/home/tlc/playbooks/plugins/lxc_ssh.py", line 822, in _run
    return self._bare_run(cmd, in_data, sudoable, checkrc)
  File "/home/tlc/playbooks/plugins/lxc_ssh.py", line 585, in _bare_run
    os.close(self.sshpass_pipe[0])
AttributeError: 'Connection' object has no attribute 'sshpass_pipe'

fatal: [play1.home]: FAILED! => {}

MSG:

Unexpected failure during module execution.
```

**Comment by andreasscherbaum** [comment] 2019-02-26 17:27
Is this error reproducible?

**Comment by tlc** [comment] 2019-02-26 21:10
Yep.

**Comment by tlc** [comment] 2019-02-27 01:54
A comment says

        # If we are using SSH password authentication, write the password into
        # the pipe we opened in _build_command.

But I don't see a pipe opened in _build_command.

**Comment by andreasscherbaum** [comment] 2019-02-27 20:57
Looks like no one used that code path before (and I just basically took that over from othe previous author).

_build_command() is never opening a pipe using sshpass_pipe, but I don't know why the code is even trying to recreate them in line 585.

@tlc Can you write a patch which will fix this problem?

**Comment by tlc** [comment] 2019-02-27 22:18
@andreasscherbaum Are you saying that use of passwords (-k) have never been tested?  But ssh keys work?

**Comment by andreasscherbaum** [comment] 2019-02-27 22:25
@tlc At least not by me. If you look at the fork history, this repo was forked from "chifflier" who wrote the initial version. I only made additional changes and updates, with help from others.

**Comment by andreasscherbaum** [comment] 2019-03-09 00:41
@tlc Do you plan to look into this issue, otherwise I plan to close it.

**Comment by tlc** [comment] 2019-03-09 13:51
You're going to close an issue because the reporter won't fix it?

**Comment by andreasscherbaum** [comment] 2019-03-09 20:35
I briefly looked into the code, but could not identify the problem. Also I don't find the use case "enter a password every time" compelling enough for a system which relies on automation all the way.

I can keep the issue open if you like, but I don't plan to spend more time on it. That's why I asked if you plan to dig deeper. If you can provide a PR which will fix the problem, I'm happy to merge it.

**Closed** 2019-03-27 12:31 UTC

**Comment by azlux** [comment] 2019-12-24 10:02
I've hit the same today. But I'm python3.
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/local/lib/python3.7/dist-packages/ansible/executor/task_executor.py", line 601, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/local/lib/python3.7/dist-packages/ansible/executor/task_executor.py", line 892, in _get_connection
    ansible_playbook_pid=to_text(os.getppid())
  File "/usr/local/lib/python3.7/dist-packages/ansible/plugins/loader.py", line 573, in get
    obj = obj(*args, **kwargs)
  File "/root/ansible/connection_plugins/lxc_ssh.py", line 137, in __init__
    (returncode2, stdout2, stderr2) = self._exec_command("which lxc", None, False)
  File "/root/ansible/connection_plugins/lxc_ssh.py", line 685, in _exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/root/ansible/connection_plugins/lxc_ssh.py", line 84, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/root/ansible/connection_plugins/lxc_ssh.py", line 664, in _run
    return self._bare_run(cmd, in_data, sudoable, checkrc)
  File "/root/ansible/connection_plugins/lxc_ssh.py", line 409, in _bare_run
    p = subprocess.Popen(cmd, stdin=slave, stdout=subprocess.PIPE, stderr=subprocess.PIPE, pass_fds=self.sshpass_pipe)
AttributeError: 'Connection' object has no attribute 'sshpass_pipe'

101 | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by andreasscherbaum** [comment] 2019-12-25 10:47
Again, if someone can provide a working PR for the issue where you enter a password all the time, I'm happy to merge it.
